// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/handler/middleware/mw_check_cookie.go
//
// Generated by this command:
//
//	mockgen -source=./internal/handler/middleware/mw_check_cookie.go -destination=./internal/handler/middleware/mocks/token_checker.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	middleware "github.com/IvanOplesnin/gofermart.git/internal/handler/middleware"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenChecker is a mock of TokenChecker interface.
type MockTokenChecker struct {
	ctrl     *gomock.Controller
	recorder *MockTokenCheckerMockRecorder
	isgomock struct{}
}

// MockTokenCheckerMockRecorder is the mock recorder for MockTokenChecker.
type MockTokenCheckerMockRecorder struct {
	mock *MockTokenChecker
}

// NewMockTokenChecker creates a new mock instance.
func NewMockTokenChecker(ctrl *gomock.Controller) *MockTokenChecker {
	mock := &MockTokenChecker{ctrl: ctrl}
	mock.recorder = &MockTokenCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenChecker) EXPECT() *MockTokenCheckerMockRecorder {
	return m.recorder
}

// CheckToken mocks base method.
func (m *MockTokenChecker) CheckToken(ctx context.Context, token string) (middleware.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckToken", ctx, token)
	ret0, _ := ret[0].(middleware.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckToken indicates an expected call of CheckToken.
func (mr *MockTokenCheckerMockRecorder) CheckToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckToken", reflect.TypeOf((*MockTokenChecker)(nil).CheckToken), ctx, token)
}
