// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/handler/orders.go
//
// Generated by this command:
//
//	mockgen -source=./internal/handler/orders.go -destination=./internal/handler/ordered_mock_test.go -package=handler
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrdered is a mock of Ordered interface.
type MockOrdered struct {
	ctrl     *gomock.Controller
	recorder *MockOrderedMockRecorder
	isgomock struct{}
}

// MockOrderedMockRecorder is the mock recorder for MockOrdered.
type MockOrderedMockRecorder struct {
	mock *MockOrdered
}

// NewMockOrdered creates a new mock instance.
func NewMockOrdered(ctrl *gomock.Controller) *MockOrdered {
	mock := &MockOrdered{ctrl: ctrl}
	mock.recorder = &MockOrderedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdered) EXPECT() *MockOrderedMockRecorder {
	return m.recorder
}

// AddOrder mocks base method.
func (m *MockOrdered) AddOrder(ctx context.Context, orderID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrder", ctx, orderID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOrder indicates an expected call of AddOrder.
func (mr *MockOrderedMockRecorder) AddOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrder", reflect.TypeOf((*MockOrdered)(nil).AddOrder), ctx, orderID)
}

// Orders mocks base method.
func (m *MockOrdered) Orders(ctx context.Context) ([]Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Orders", ctx)
	ret0, _ := ret[0].([]Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Orders indicates an expected call of Orders.
func (mr *MockOrderedMockRecorder) Orders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Orders", reflect.TypeOf((*MockOrdered)(nil).Orders), ctx)
}
