// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/handler/withdraw.go
//
// Generated by this command:
//
//	mockgen -source=./internal/handler/withdraw.go -destination=./internal/handler/withdrawer_mock_test.go -package=handler
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWithdrawer is a mock of Withdrawer interface.
type MockWithdrawer struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawerMockRecorder
	isgomock struct{}
}

// MockWithdrawerMockRecorder is the mock recorder for MockWithdrawer.
type MockWithdrawerMockRecorder struct {
	mock *MockWithdrawer
}

// NewMockWithdrawer creates a new mock instance.
func NewMockWithdrawer(ctrl *gomock.Controller) *MockWithdrawer {
	mock := &MockWithdrawer{ctrl: ctrl}
	mock.recorder = &MockWithdrawerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawer) EXPECT() *MockWithdrawerMockRecorder {
	return m.recorder
}

// ListWithdraws mocks base method.
func (m *MockWithdrawer) ListWithdraws(ctx context.Context) ([]Withdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithdraws", ctx)
	ret0, _ := ret[0].([]Withdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithdraws indicates an expected call of ListWithdraws.
func (mr *MockWithdrawerMockRecorder) ListWithdraws(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithdraws", reflect.TypeOf((*MockWithdrawer)(nil).ListWithdraws), ctx)
}

// Withdraw mocks base method.
func (m *MockWithdrawer) Withdraw(ctx context.Context, orderNumber string, summa float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, orderNumber, summa)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockWithdrawerMockRecorder) Withdraw(ctx, orderNumber, summa any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockWithdrawer)(nil).Withdraw), ctx, orderNumber, summa)
}
