// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/gophermart/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/gophermart/interfaces.go -destination=./internal/service/gophermart/mocks.go -package=gophermart
//

// Package gophermart is a generated GoMock package.
package gophermart

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockUserCRUD is a mock of UserCRUD interface.
type MockUserCRUD struct {
	ctrl     *gomock.Controller
	recorder *MockUserCRUDMockRecorder
	isgomock struct{}
}

// MockUserCRUDMockRecorder is the mock recorder for MockUserCRUD.
type MockUserCRUDMockRecorder struct {
	mock *MockUserCRUD
}

// NewMockUserCRUD creates a new mock instance.
func NewMockUserCRUD(ctrl *gomock.Controller) *MockUserCRUD {
	mock := &MockUserCRUD{ctrl: ctrl}
	mock.recorder = &MockUserCRUDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCRUD) EXPECT() *MockUserCRUDMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockUserCRUD) AddUser(ctx context.Context, login, passwordHash string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, login, passwordHash)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUser indicates an expected call of AddUser.
func (mr *MockUserCRUDMockRecorder) AddUser(ctx, login, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockUserCRUD)(nil).AddUser), ctx, login, passwordHash)
}

// GetUserByID mocks base method.
func (m *MockUserCRUD) GetUserByID(ctx context.Context, id int32) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserCRUDMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserCRUD)(nil).GetUserByID), ctx, id)
}

// GetUserByLogin mocks base method.
func (m *MockUserCRUD) GetUserByLogin(ctx context.Context, login string) (User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockUserCRUDMockRecorder) GetUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockUserCRUD)(nil).GetUserByLogin), ctx, login)
}

// MockUserGetter is a mock of UserGetter interface.
type MockUserGetter struct {
	ctrl     *gomock.Controller
	recorder *MockUserGetterMockRecorder
	isgomock struct{}
}

// MockUserGetterMockRecorder is the mock recorder for MockUserGetter.
type MockUserGetterMockRecorder struct {
	mock *MockUserGetter
}

// NewMockUserGetter creates a new mock instance.
func NewMockUserGetter(ctrl *gomock.Controller) *MockUserGetter {
	mock := &MockUserGetter{ctrl: ctrl}
	mock.recorder = &MockUserGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserGetter) EXPECT() *MockUserGetterMockRecorder {
	return m.recorder
}

// MockHasher is a mock of Hasher interface.
type MockHasher struct {
	ctrl     *gomock.Controller
	recorder *MockHasherMockRecorder
	isgomock struct{}
}

// MockHasherMockRecorder is the mock recorder for MockHasher.
type MockHasherMockRecorder struct {
	mock *MockHasher
}

// NewMockHasher creates a new mock instance.
func NewMockHasher(ctrl *gomock.Controller) *MockHasher {
	mock := &MockHasher{ctrl: ctrl}
	mock.recorder = &MockHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHasher) EXPECT() *MockHasherMockRecorder {
	return m.recorder
}

// ComparePasswordHash mocks base method.
func (m *MockHasher) ComparePasswordHash(password, hash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComparePasswordHash", password, hash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComparePasswordHash indicates an expected call of ComparePasswordHash.
func (mr *MockHasherMockRecorder) ComparePasswordHash(password, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComparePasswordHash", reflect.TypeOf((*MockHasher)(nil).ComparePasswordHash), password, hash)
}

// HashPassword mocks base method.
func (m *MockHasher) HashPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockHasherMockRecorder) HashPassword(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockHasher)(nil).HashPassword), password)
}

// MockGetAPIOrdered is a mock of GetAPIOrdered interface.
type MockGetAPIOrdered struct {
	ctrl     *gomock.Controller
	recorder *MockGetAPIOrderedMockRecorder
	isgomock struct{}
}

// MockGetAPIOrderedMockRecorder is the mock recorder for MockGetAPIOrdered.
type MockGetAPIOrderedMockRecorder struct {
	mock *MockGetAPIOrdered
}

// NewMockGetAPIOrdered creates a new mock instance.
func NewMockGetAPIOrdered(ctrl *gomock.Controller) *MockGetAPIOrdered {
	mock := &MockGetAPIOrdered{ctrl: ctrl}
	mock.recorder = &MockGetAPIOrderedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAPIOrdered) EXPECT() *MockGetAPIOrderedMockRecorder {
	return m.recorder
}

// GetOrder mocks base method.
func (m *MockGetAPIOrdered) GetOrder(ctx context.Context, number string) (*AccrualResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, number)
	ret0, _ := ret[0].(*AccrualResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockGetAPIOrderedMockRecorder) GetOrder(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockGetAPIOrdered)(nil).GetOrder), ctx, number)
}

// MockOrdered is a mock of Ordered interface.
type MockOrdered struct {
	ctrl     *gomock.Controller
	recorder *MockOrderedMockRecorder
	isgomock struct{}
}

// MockOrderedMockRecorder is the mock recorder for MockOrdered.
type MockOrderedMockRecorder struct {
	mock *MockOrdered
}

// NewMockOrdered creates a new mock instance.
func NewMockOrdered(ctrl *gomock.Controller) *MockOrdered {
	mock := &MockOrdered{ctrl: ctrl}
	mock.recorder = &MockOrderedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdered) EXPECT() *MockOrderedMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrdered) CreateOrder(ctx context.Context, userID int32, number string) (bool, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, userID, number)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderedMockRecorder) CreateOrder(ctx, userID, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrdered)(nil).CreateOrder), ctx, userID, number)
}

// GetOrders mocks base method.
func (m *MockOrdered) GetOrders(ctx context.Context, userID int32) ([]Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, userID)
	ret0, _ := ret[0].([]Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockOrderedMockRecorder) GetOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockOrdered)(nil).GetOrders), ctx, userID)
}

// MockListUpdateApplyAccrual is a mock of ListUpdateApplyAccrual interface.
type MockListUpdateApplyAccrual struct {
	ctrl     *gomock.Controller
	recorder *MockListUpdateApplyAccrualMockRecorder
	isgomock struct{}
}

// MockListUpdateApplyAccrualMockRecorder is the mock recorder for MockListUpdateApplyAccrual.
type MockListUpdateApplyAccrualMockRecorder struct {
	mock *MockListUpdateApplyAccrual
}

// NewMockListUpdateApplyAccrual creates a new mock instance.
func NewMockListUpdateApplyAccrual(ctrl *gomock.Controller) *MockListUpdateApplyAccrual {
	mock := &MockListUpdateApplyAccrual{ctrl: ctrl}
	mock.recorder = &MockListUpdateApplyAccrualMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListUpdateApplyAccrual) EXPECT() *MockListUpdateApplyAccrualMockRecorder {
	return m.recorder
}

// ApplyAccrual mocks base method.
func (m *MockListUpdateApplyAccrual) ApplyAccrual(ctx context.Context, number string, accrual int64, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyAccrual", ctx, number, accrual, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyAccrual indicates an expected call of ApplyAccrual.
func (mr *MockListUpdateApplyAccrualMockRecorder) ApplyAccrual(ctx, number, accrual, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyAccrual", reflect.TypeOf((*MockListUpdateApplyAccrual)(nil).ApplyAccrual), ctx, number, accrual, userID)
}

// ListPending mocks base method.
func (m *MockListUpdateApplyAccrual) ListPending(ctx context.Context, limit int32, statuses []string, timeSync time.Time) ([]Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx, limit, statuses, timeSync)
	ret0, _ := ret[0].([]Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockListUpdateApplyAccrualMockRecorder) ListPending(ctx, limit, statuses, timeSync any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockListUpdateApplyAccrual)(nil).ListPending), ctx, limit, statuses, timeSync)
}

// UpdateFromAccrual mocks base method.
func (m *MockListUpdateApplyAccrual) UpdateFromAccrual(ctx context.Context, number, status string, nextSync time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFromAccrual", ctx, number, status, nextSync)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFromAccrual indicates an expected call of UpdateFromAccrual.
func (mr *MockListUpdateApplyAccrualMockRecorder) UpdateFromAccrual(ctx, number, status, nextSync any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFromAccrual", reflect.TypeOf((*MockListUpdateApplyAccrual)(nil).UpdateFromAccrual), ctx, number, status, nextSync)
}

// UpdateSyncTime mocks base method.
func (m *MockListUpdateApplyAccrual) UpdateSyncTime(ctx context.Context, number string, nextSync time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncTime", ctx, number, nextSync)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSyncTime indicates an expected call of UpdateSyncTime.
func (mr *MockListUpdateApplyAccrualMockRecorder) UpdateSyncTime(ctx, number, nextSync any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncTime", reflect.TypeOf((*MockListUpdateApplyAccrual)(nil).UpdateSyncTime), ctx, number, nextSync)
}
