// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderNumber struct {
	ID         int32
	Number     string
	UserID     int32
	Status     string
	Accrual    pgtype.Numeric
	UploadedAt pgtype.Timestamptz
}

type User struct {
	ID           int32
	Login        string
	PasswordHash string
}

type UserBalance struct {
	ID        int32
	UserID    int32
	Balance   pgtype.Numeric
	Withdrawn pgtype.Numeric
}

type Withdraw struct {
	ID          int32
	UserID      int32
	OrderNumber string
	Summa       pgtype.Numeric
	ProcessedAt pgtype.Timestamptz
}
