// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package query

import (
	"context"
)

const addUser = `-- name: AddUser :one
INSERT INTO users ("login", password_hash)
VALUES ($1, $2)
RETURNING id
`

type AddUserParams struct {
	Login        string
	PasswordHash string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, addUser, arg.Login, arg.PasswordHash)
	var id int32
	err := row.Scan(&id)
	return id, err
}
