// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrder = `-- name: AddOrder :exec
INSERT INTO order_numbers (user_id, "number", "status", uploaded_at)
VALUES ($1, $2, $3, $4)
`

type AddOrderParams struct {
	UserID     int32
	Number     string
	Status     string
	UploadedAt pgtype.Timestamptz
}

func (q *Queries) AddOrder(ctx context.Context, arg AddOrderParams) error {
	_, err := q.db.Exec(ctx, addOrder,
		arg.UserID,
		arg.Number,
		arg.Status,
		arg.UploadedAt,
	)
	return err
}

const addUser = `-- name: AddUser :one
INSERT INTO users ("login", password_hash)
VALUES ($1, $2)
RETURNING id
`

type AddUserParams struct {
	Login        string
	PasswordHash string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, addUser, arg.Login, arg.PasswordHash)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, user_id, "number", "status", uploaded_at
FROM order_numbers
WHERE "number" = $1
LIMIT 1
`

type GetOrderByNumberRow struct {
	ID         int32
	UserID     int32
	Number     string
	Status     string
	UploadedAt pgtype.Timestamptz
}

func (q *Queries) GetOrderByNumber(ctx context.Context, number string) (GetOrderByNumberRow, error) {
	row := q.db.QueryRow(ctx, getOrderByNumber, number)
	var i GetOrderByNumberRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Number,
		&i.Status,
		&i.UploadedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	err := row.Scan(&id)
	return id, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, "login", password_hash
FROM users
WHERE "login" = $1
LIMIT 1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(&i.ID, &i.Login, &i.PasswordHash)
	return i, err
}
